// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'keys.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'sdk.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `with_state_transition`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BuilderState`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Builder>>
abstract class Builder implements RustOpaqueInterface {
  /// Attempts to connect using the provided app key. Returns the SDK if the
  /// key is recognized by the indexer, otherwise `None`.
  Future<Sdk?> connected({required AppKey appKey});

  /// Creates a new SDK builder targeting the provided indexer URL.
  factory Builder({required String indexerUrl, required AppMetadata appMeta}) =>
      RustLib.instance.api.crateApiBuilderBuilderNew(
        indexerUrl: indexerUrl,
        appMeta: appMeta,
      );

  /// Registers the application with the indexer using the provided
  /// recovery phrase. Returns the live SDK.
  Future<Sdk> register({required String mnemonic});

  /// Requests connection approval for the application. Transitions the
  /// builder into the requesting-approval state.
  Future<void> requestConnection();

  /// Returns the URL at which the user must approve the connection request.
  /// Only valid after [Builder::request_connection].
  String responseUrl();

  /// Blocks until the connection request is approved by the user.
  Future<void> waitForApproval();
}
