// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generates a new BIP-39 12-word recovery phrase.
String generateRecoveryPhrase() =>
    RustLib.instance.api.crateApiKeysGenerateRecoveryPhrase();

/// Validates a BIP-39 recovery phrase.
void validateRecoveryPhrase({required String phrase}) =>
    RustLib.instance.api.crateApiKeysValidateRecoveryPhrase(phrase: phrase);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppKey>>
abstract class AppKey implements RustOpaqueInterface {
  /// Exports the AppKey as a 32-byte buffer.
  Uint8List export_();

  /// Imports an AppKey from a 32-byte buffer.
  factory AppKey({required List<int> key}) =>
      RustLib.instance.api.crateApiKeysAppKeyNew(key: key);

  /// Returns the public key corresponding to the AppKey, hex-encoded.
  String publicKey();

  /// Signs a message using the AppKey.
  Uint8List sign({required List<int> message});

  /// Verifies a signature for a given message using the AppKey.
  bool verifySignature({
    required List<int> message,
    required List<int> signature,
  });
}
