// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'keys.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `sealed_from_native`, `sealed_to_native`, `slab_from_native`, `slab_to_native`, `snapshot`

/// Calculates the encoded size of data given the original size and erasure
/// coding parameters.
BigInt encodedSize({
  required BigInt size,
  required int dataShards,
  required int parityShards,
}) => RustLib.instance.api.crateApiObjectEncodedSize(
  size: size,
  dataShards: dataShards,
  parityShards: parityShards,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ObjectEvent>>
abstract class ObjectEvent implements RustOpaqueInterface {
  bool get deleted;

  String get id;

  PinnedObject? get object;

  DateTime get updatedAt;
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PinnedObject>>
abstract class PinnedObject implements RustOpaqueInterface {
  /// Returns the time the object was created.
  DateTime createdAt();

  static Future<PinnedObject> default_() =>
      RustLib.instance.api.crateApiObjectPinnedObjectDefault();

  /// Returns the total encoded size after erasure coding.
  BigInt encodedSize();

  /// Returns the object's ID, hex-encoded.
  String id();

  /// Returns the user-supplied metadata associated with the object.
  Uint8List metadata();

  /// Creates a new empty object.
  factory PinnedObject() =>
      RustLib.instance.api.crateApiObjectPinnedObjectNew();

  /// Opens a sealed object using the provided app key.
  static PinnedObject open({
    required AppKey appKey,
    required SealedObject sealed,
  }) => RustLib.instance.api.crateApiObjectPinnedObjectOpen(
    appKey: appKey,
    sealed: sealed,
  );

  /// Seals the object for offline storage.
  SealedObject seal({required AppKey appKey});

  /// Returns the total size of the object in bytes.
  BigInt size();

  /// Returns the slabs that make up the object.
  List<Slab> slabs();

  /// Replaces the user-supplied metadata.
  void updateMetadata({required List<int> metadata});

  /// Returns the time the object was last updated.
  DateTime updatedAt();
}
