// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `build`, `build`, `shard_progress_from_native`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DownloadOptions>>
abstract class DownloadOptions implements RustOpaqueInterface {
  /// Constructs a [DownloadOptions] handle. All primitive arguments are
  /// optional; `None` keeps the SDK default.
  factory DownloadOptions({int? maxInflight, BigInt? offset, BigInt? length}) =>
      RustLib.instance.api.crateApiOptionsDownloadOptionsNew(
        maxInflight: maxInflight,
        offset: offset,
        length: length,
      );

  /// Subscribe to per-shard download progress. Returns a stream that emits
  /// one event per completed shard.
  Stream<ShardProgress> shardProgress();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UploadOptions>>
abstract class UploadOptions implements RustOpaqueInterface {
  /// Constructs an [UploadOptions] handle. All primitive arguments are
  /// optional; `None` keeps the SDK default.
  factory UploadOptions({
    int? dataShards,
    int? parityShards,
    int? maxInflight,
  }) => RustLib.instance.api.crateApiOptionsUploadOptionsNew(
    dataShards: dataShards,
    parityShards: parityShards,
    maxInflight: maxInflight,
  );

  /// Subscribe to per-shard upload progress. Returns a stream that emits
  /// one event per completed shard.
  Stream<ShardProgress> shardProgress();
}
