// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'keys.dart';
import 'object.dart';
import 'options.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `account_from_native`, `host_from_native`, `pinned_slab_from_native`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Sdk>>
abstract class Sdk implements RustOpaqueInterface {
  /// Returns the current account.
  Future<Account> account();

  /// Returns the application key used by the SDK.
  AppKey appKey();

  /// Deletes an object from the indexer.
  Future<void> deleteObject({required String key});

  /// Downloads an object from the Sia network as a stream of byte chunks.
  Stream<Uint8List> download({
    required PinnedObject object,
    required DownloadOptions options,
  });

  /// Returns a list of all usable hosts.
  Future<List<Host>> hosts();

  /// Returns metadata about a specific object.
  Future<PinnedObject> object({required String key});

  /// Returns object events from the indexer for syncing.
  Future<List<ObjectEvent>> objectEvents({
    ObjectsCursor? cursor,
    required int limit,
  });

  /// Pins an object to the indexer.
  Future<void> pinObject({required PinnedObject object});

  /// Unpins slabs not used by any object on the account.
  Future<void> pruneSlabs();

  /// Creates a signed URL for sharing an object until `valid_until`.
  String shareObject({
    required PinnedObject object,
    required DateTime validUntil,
  });

  /// Retrieves a shared object from a signed URL.
  Future<PinnedObject> sharedObject({required String sharedUrl});

  /// Returns metadata about a slab.
  Future<PinnedSlab> slab({required String slabId});

  /// Updates the metadata of an object stored in the indexer.
  Future<void> updateObjectMetadata({required PinnedObject object});

  /// Uploads an object to the Sia network by streaming bytes from a Dart
  /// pull callback. The callback returns the next chunk; an empty or `null`
  /// result signals EOF.
  ///
  /// Pass a fresh [PinnedObject::new] for new uploads. To resume or append
  /// to a previous upload, pass the object returned from the prior call.
  /// Note that appending changes the object's ID; the object must be
  /// re-pinned afterwards and any cached references updated.
  Future<PinnedObject> upload({
    required PinnedObject object,
    required FutureOr<Uint8List?> Function() source,
    required UploadOptions options,
  });
}
