// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

/// An account registered on the indexer.
class Account {
  final String accountKey;
  final BigInt maxPinnedData;
  final BigInt remainingStorage;
  final BigInt pinnedData;
  final BigInt pinnedSize;
  final bool ready;
  final App app;
  final DateTime lastUsed;

  const Account({
    required this.accountKey,
    required this.maxPinnedData,
    required this.remainingStorage,
    required this.pinnedData,
    required this.pinnedSize,
    required this.ready,
    required this.app,
    required this.lastUsed,
  });

  @override
  int get hashCode =>
      accountKey.hashCode ^
      maxPinnedData.hashCode ^
      remainingStorage.hashCode ^
      pinnedData.hashCode ^
      pinnedSize.hashCode ^
      ready.hashCode ^
      app.hashCode ^
      lastUsed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Account &&
          runtimeType == other.runtimeType &&
          accountKey == other.accountKey &&
          maxPinnedData == other.maxPinnedData &&
          remainingStorage == other.remainingStorage &&
          pinnedData == other.pinnedData &&
          pinnedSize == other.pinnedSize &&
          ready == other.ready &&
          app == other.app &&
          lastUsed == other.lastUsed;
}

/// The protocol used in a network address.
enum AddressProtocol { siaMux, quic }

/// Application info.
class App {
  final String id;
  final String name;
  final String description;
  final String? serviceUrl;
  final String? logoUrl;

  const App({
    required this.id,
    required this.name,
    required this.description,
    this.serviceUrl,
    this.logoUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      serviceUrl.hashCode ^
      logoUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is App &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          serviceUrl == other.serviceUrl &&
          logoUrl == other.logoUrl;
}

/// Metadata about an application connecting to the indexer.
class AppMetadata {
  final Uint8List id;
  final String name;
  final String description;
  final String serviceUrl;
  final String? logoUrl;
  final String? callbackUrl;

  const AppMetadata({
    required this.id,
    required this.name,
    required this.description,
    required this.serviceUrl,
    this.logoUrl,
    this.callbackUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      serviceUrl.hashCode ^
      logoUrl.hashCode ^
      callbackUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppMetadata &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          serviceUrl == other.serviceUrl &&
          logoUrl == other.logoUrl &&
          callbackUrl == other.callbackUrl;
}

/// Information about a storage provider on the Sia network.
class Host {
  final String publicKey;
  final List<NetAddress> addresses;
  final String countryCode;
  final double latitude;
  final double longitude;
  final bool goodForUpload;

  const Host({
    required this.publicKey,
    required this.addresses,
    required this.countryCode,
    required this.latitude,
    required this.longitude,
    required this.goodForUpload,
  });

  @override
  int get hashCode =>
      publicKey.hashCode ^
      addresses.hashCode ^
      countryCode.hashCode ^
      latitude.hashCode ^
      longitude.hashCode ^
      goodForUpload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Host &&
          runtimeType == other.runtimeType &&
          publicKey == other.publicKey &&
          addresses == other.addresses &&
          countryCode == other.countryCode &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          goodForUpload == other.goodForUpload;
}

/// A network address of a storage provider on the Sia network.
class NetAddress {
  final AddressProtocol protocol;
  final String address;

  const NetAddress({required this.protocol, required this.address});

  @override
  int get hashCode => protocol.hashCode ^ address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetAddress &&
          runtimeType == other.runtimeType &&
          protocol == other.protocol &&
          address == other.address;
}

/// A cursor for paginating through objects.
class ObjectsCursor {
  final String id;
  final DateTime after;

  const ObjectsCursor({required this.id, required this.after});

  @override
  int get hashCode => id.hashCode ^ after.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ObjectsCursor &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          after == other.after;
}

/// A sector stored on a specific host.
class PinnedSector {
  final String root;
  final String hostKey;

  const PinnedSector({required this.root, required this.hostKey});

  @override
  int get hashCode => root.hashCode ^ hostKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PinnedSector &&
          runtimeType == other.runtimeType &&
          root == other.root &&
          hostKey == other.hostKey;
}

/// A pinned slab from the indexer.
class PinnedSlab {
  final String id;
  final Uint8List encryptionKey;
  final int minShards;
  final List<PinnedSector> sectors;

  const PinnedSlab({
    required this.id,
    required this.encryptionKey,
    required this.minShards,
    required this.sectors,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      encryptionKey.hashCode ^
      minShards.hashCode ^
      sectors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PinnedSlab &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          encryptionKey == other.encryptionKey &&
          minShards == other.minShards &&
          sectors == other.sectors;
}

/// A sealed object for offline storage.
class SealedObject {
  final String id;
  final Uint8List encryptedDataKey;
  final Uint8List encryptedMetadataKey;
  final List<Slab> slabs;
  final Uint8List encryptedMetadata;
  final Uint8List dataSignature;
  final Uint8List metadataSignature;
  final DateTime createdAt;
  final DateTime updatedAt;

  const SealedObject({
    required this.id,
    required this.encryptedDataKey,
    required this.encryptedMetadataKey,
    required this.slabs,
    required this.encryptedMetadata,
    required this.dataSignature,
    required this.metadataSignature,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      encryptedDataKey.hashCode ^
      encryptedMetadataKey.hashCode ^
      slabs.hashCode ^
      encryptedMetadata.hashCode ^
      dataSignature.hashCode ^
      metadataSignature.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SealedObject &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          encryptedDataKey == other.encryptedDataKey &&
          encryptedMetadataKey == other.encryptedMetadataKey &&
          slabs == other.slabs &&
          encryptedMetadata == other.encryptedMetadata &&
          dataSignature == other.dataSignature &&
          metadataSignature == other.metadataSignature &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// Progress information about a successfully uploaded or downloaded shard.
class ShardProgress {
  final String hostKey;
  final int shardSize;
  final int shardIndex;
  final int slabIndex;
  final double elapsedMs;

  const ShardProgress({
    required this.hostKey,
    required this.shardSize,
    required this.shardIndex,
    required this.slabIndex,
    required this.elapsedMs,
  });

  @override
  int get hashCode =>
      hostKey.hashCode ^
      shardSize.hashCode ^
      shardIndex.hashCode ^
      slabIndex.hashCode ^
      elapsedMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShardProgress &&
          runtimeType == other.runtimeType &&
          hostKey == other.hostKey &&
          shardSize == other.shardSize &&
          shardIndex == other.shardIndex &&
          slabIndex == other.slabIndex &&
          elapsedMs == other.elapsedMs;
}

/// A slab representing a contiguous erasure-coded segment of a file.
class Slab {
  final Uint8List encryptionKey;
  final int minShards;
  final List<PinnedSector> sectors;
  final int offset;
  final int length;

  const Slab({
    required this.encryptionKey,
    required this.minShards,
    required this.sectors,
    required this.offset,
    required this.length,
  });

  @override
  int get hashCode =>
      encryptionKey.hashCode ^
      minShards.hashCode ^
      sectors.hashCode ^
      offset.hashCode ^
      length.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Slab &&
          runtimeType == other.runtimeType &&
          encryptionKey == other.encryptionKey &&
          minShards == other.minShards &&
          sectors == other.sectors &&
          offset == other.offset &&
          length == other.length;
}
