// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'object.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `with`

/// Adds an object to the upload by streaming bytes from a Dart pull callback.
/// The callback returns the next chunk; an empty or `null` result signals EOF.
/// Returns the number of bytes consumed.
///
/// If the reader errors part-way, no object is registered for the failed call
/// and the upload may still be continued or finalized. Objects are returned in
/// add order from [PackedUpload::finalize].
Future<BigInt> packedUploadAdd({
  required PackedUpload upload,
  required FutureOr<Uint8List?> Function() source,
}) => RustLib.instance.api.crateApiUploadPackedUploadAdd(
  upload: upload,
  source: source,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PackedUpload>>
abstract class PackedUpload implements RustOpaqueInterface {
  /// Finalizes the upload, flushing all packed slabs to hosts, and returns
  /// the resulting objects in the order they were added. The objects must be
  /// pinned to the indexer afterwards. The handle cannot be used again.
  Future<List<PinnedObject>> finalize();

  /// Returns the cumulative length in bytes of all objects added so far.
  BigInt length();

  /// Returns the optimal size in bytes of each packed slab.
  BigInt optimalDataSize();

  /// Returns the number of bytes remaining until the current slab reaches its
  /// optimal packed size. Adding an object larger than this starts a new
  /// slab; prioritize objects that fit to minimize padding.
  BigInt remaining();

  /// Returns the number of slabs the upload will produce once finalized.
  BigInt slabs();
}
